### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by ganping** [dmansfield/passport-negotiate#1]
TypeError: this._native_kerberos.authGSSServerInit is not a function
    at Kerberos.authGSSServerInit (C:\Projects\eem\eem\node_modules\kerberos\lib\kerberos.js:95:32)
    at Strategy.authenticate (C:\Projects\eem\eem\node_modules\passport-negotiate\lib\passport-negotiate\strategy.js:104:11)
    at attempt (C:\Projects\eem\eem\node_modules\passport\lib\middleware\authenticate.js:341:16)

All following methods are missing in lib\win32\kerberos.cc
  Nan::SetPrototypeMethod(t, "authGSSClientInit", AuthGSSClientInit);
  Nan::SetPrototypeMethod(t, "authGSSClientStep", AuthGSSClientStep);
  Nan::SetPrototypeMethod(t, "authGSSClientUnwrap", AuthGSSClientUnwrap);
  Nan::SetPrototypeMethod(t, "authGSSClientWrap", AuthGSSClientWrap);
  Nan::SetPrototypeMethod(t, "authGSSClientClean", AuthGSSClientClean);
  Nan::SetPrototypeMethod(t, "authGSSServerInit", AuthGSSServerInit);
  Nan::SetPrototypeMethod(t, "authGSSServerClean", AuthGSSServerClean);
  Nan::SetPrototypeMethod(t, "authGSSServerStep", AuthGSSServerStep);

**Comment by dmansfield** [comment]
I'll try to look into this.  The underlying module (kerberos) doesn't seem to support the necessary methods on windows.

**Comment by francescoinfante** [comment]
any update on this issue? I'm really interested in making this module works on windows

I actually tried the example and encountered the same error.

**Comment by simon-p-r** [comment]
Yes I am getting same error, it doesn't work on Windows

**Comment by barathank** [comment]
I am getting the same error on the Linux machine as well, is there a pre-requisite that needs to be installed in the system to use kerberos?

**Comment by logan-dunbar** [comment]
@barathank I managed to get it working on RHEL6 with the following packages: `krb5-workstation`, `krb5-libs`, `krb5-devel`, and then because it requires a c++ 11 compiler and the default that comes with RHEL6 is gcc-4.4.7 I had to install `devtoolset-3-toolchain` as well, and run the command as such: `source /opt/rh/devtoolset-3/enable && npm i kerberos`

I would also like to have this working in windows as we develop on windows machines but deploy to linux boxes. Any update on this?
